---
abstract: 'The comparison benchmarker'
author:
  - 'Dai Okabayashi <bayashi@cpan.org>'
build_requires:
  Test::More: 0.88
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Benchmarks
provides:
  Benchmarks:
    file: lib/Benchmarks.pm
    version: 0.06
requires:
  Benchmark: 1.07
  perl: 5.008001
resources:
  bugtracker: http://github.com/bayashi/Benchmarks/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/bayashi/Benchmarks
version: 0.06
